# Generated by Django 2.2.27 on 2022-02-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail institucional')),
                ('turma', models.IntegerField(verbose_name='Turma')),
                ('curso', models.CharField(max_length=25, verbose_name='Curso')),
                ('senha', models.CharField(max_length=12, verbose_name='Senha')),
            ],
        ),
    ]
